#!/bin/bash

help() {
  echo "  支持参数
  {{}}
  "
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
  -v | --version)
    VERSION="$2"
    shift 2
    ;;
  -h | --help)
    help
    exit 1
    ;;
  *)
    echo "Unknown option $1"
    exit 1
    ;;
  esac
done

if [ -z "$VERSION" ]; then
  VERSION=1
fi

echo "VERSION=$VERSION"

#
#
#
#
#
#
#
#

